name: 그 외 문의
description: 질문·문서 오타·기타
title: "[문의] "
assignees: [zxc88kr]
body:
  - type: textarea
    id: body
    attributes:
      label: 내용
      description: 버그·기능이 아닌 무엇이든 자유롭게 적어주세요.
      placeholder: 사용법이 궁금하거나, 문서에서 이상한 부분을 발견했어요
    validations:
      required: true
